[platformio]
default_envs = esp32dev
data_dir = data/littlefs

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; Match Arduino IDE partition setting: Huge APP (3MB No OTA)
board_build.partitions = huge_app.csv

; Use the existing LittleFS web assets directory for uploadfs.
board_build.filesystem = littlefs

lib_deps =
  knolleary/PubSubClient @ ^2.8
